language: java
jdk:
- openjdk7
- oraclejdk8
sudo: false
before_install:
- cp ./etc/settings.xml ~/.m2/
- cp ./etc/onFailure.sh  ~/
- cp ./etc/onSuccess.sh  ~/
- chmod 777 ~/onFailure.sh
- chmod 777 ~/onSuccess.sh
script:
- mvn -B clean verify
after_failure: ~/onFailure.sh
after_success: ~/onSuccess.sh
after_script:
- mvn -B cobertura:cobertura coveralls:report
notifications:
  email: false
  irc:
    channels:
    - chat.freenode.net#lightblue
  on_success: always
env:
  global:
  - secure: oa9tlT0C/yBTP4/NLF1ptsMsAanx8Hs/apl/s4z9OZ/ZeFvGpZ4CbD7WMrEzCp36uqEfEeaL9BthMQQxH2uRPLvoaopTGW2sgTL8FvCm4POWSH4nelucoC5RnseXGeYgs64zGUmYTrn3isvNZmfUCbRT8B/xsQts92kz8Pt5XwSTWXJeuv9DRSlrDNO3JORr97xnDPErCzFX3McNXZLe4KfRP7wtmuIphEIMS2hViTh/eJoklsa21AftBvbKkF3IamsoXg2/yhlbgUMts04OyE38erw+RrWlYO0MkivDF4xdVTrnOB2TEeL3WBsm8AX0QtloRa2LVz58y+XdSMZb5oRGJ8Pbhu+8+CKKdKfw2WgXd0mUyWepZ4E3YWh2bRe7LTPRHyaxMbZGt1blS7JjrJp88BYKCdKAivnQ90GKEQVEcXcz4iFszW1dX3aj980xb2rhqzWHlDMhXPGEWArDOyFlXxZ0hkguLG+SiHvsh5cEfbNTGuENdraqalUvSQXoIqiOxJCRx6fNgbSibbYv3jU2z9YiBs83B7LJZBYBrf9N3WiJrfzV92KqnDDsUd0J5sYzTJ2nOvfb3BBzKozRmBidx+EZlvxpzB5Z6KB60oNctiWEktZTZSGtW9Eztv++TNYlOtRae6P7laTa1Og0w4geK0ONeIdCp6t5LNdsvpc=
  - secure: eTu5jQL/HuzKz4MwhVT5FtMaDY1HEMNYeVfxEs9OVHQ9CKnFlJxBeWXTb/FEpDJO+1O7LB0URWWfCABchafp6ZUKhu7DcDys2AeICtv6nkkf1n9Lb7NjR+Ku4XPmugKZq+Nk9q5ZWgKCzoFE/mfxdWYZfX/0rouHYvDaj6dA9plEbbfsQ9j0UaehkUajMgNwCU6jwujlKIZ2FHQ53ESFYwYu6/Wle+m+pi9+dos5ogjS/LR0ZqZH/A9yCu2qOXtGsUvSgO3k5sWxTOwpaTobgBzFEB7M/9m53arN1L5sos+1qqcBvzwX9ps4EXGFC9NoWuDD0hf7ubOpRB8GOXrSGDOBsHEpnDKGUSbS/MWrgVxqjuXKRk6cQvsr32Ytvdjf82KeGkO/tY/5JnFWSDYiX2QW2ux5Gy9BrgVcP8XNKZrua6Vkr+ALehJ33PFT7qKcRqVlY0MQsrulSs484BdU9IunjIVaiFymmoZ5flzSUqtarPs9EAOaLvfD5jFiBCG/n086j9PA6ISEDZH2eNyM3Ji6AsA6rSReVeIGOZJqEieTxbnX90tav6+YRu/lpqttQDuY43PJyOevssfzgOu6cy0s3kyr6Oa/5ab6258mhaMKr4JXFkrzIaIokG9AGNvMLkJKhl+4uYwqSkuskXBYlv36YvSD3XsFmcgJBTuxR/o=
