language: java
jdk:
- openjdk7
- oraclejdk8
sudo: false
before_install:
- cp ./etc/settings.xml ~/.m2/
- cp ./etc/onFailure.sh  ~/
- cp ./etc/onSuccess.sh  ~/
- chmod 777 ~/onFailure.sh
- chmod 777 ~/onSuccess.sh
script:
- mvn -B clean verify
after_failure: "~/onFailure.sh"
after_success: "~/onSuccess.sh"
after_script:
- mvn -B cobertura:cobertura coveralls:report
notifications:
  email: false
  irc:
    channels:
    - chat.freenode.net#lightblue
  on_success: always
env:
  global:
  - secure: n/SXAo4GEqavxKtzv3f7Gyf/m/6fsupnilRdSmI3JarxBw4pfHIm9tmAAsQWCVMgJNz0mfhecXZakfucJztl4wlsaBhCA/aig8cprOJsF0+IRdlaDR2hbjJnHtJVS5TqvXyXDsui9UNCGfUSz4lBl7JmHQleQTJ1ZXhSgGHbqFiOOw8CZnLdFwjI97+iqCmME3U2dkBFp2RFnk6fvLk5IiSsUZBJnGBhtowGb7FfMpgh96oh4RRaSUyAD+T3CIdaAIlTMQJUy7JmE9CcG/FQea5BlKcTpyXakhRfPJg7GxR5UrjWZa7GTIiQLYP2kudJdTJ8d/hfEpdnV/Mo7MiJC0LvhDhY8MIOnFpCbYxMy5ltcr7jql+l+xFSqtuLiOYcnlUMtgh1Y5b73RJ8RIO0VHUdKa2QlMcHr+SyLGY5jqJ6teex0pFsG7fojltEWPxx8VGiflbsJ7El+iJP7+wljVeQ8/IDgXDtL3gUqTKgpU/k8JshLp92jgnEWYrIDYOTk1zGIRYtCxmDqverk/W11JbOnqLUeNarvHw6gyb9qymkbtuPYFaf3iqOx3zXz1jXaXhrOgqdMDkLGOJdUCfY7o9h2cNnNC5/gG3lKm4UZIitNkpwad3JOo+HtVbg6Icb4RrVzLgbOBhiJ0sSzuyLrMpPN/4NXhSw5/7RlGCKB2U=
  - secure: ZZEoVZzYO2+KMHqScEmP2weWXIIFFc6dQ3Z0scW40sJZjFR/3U6WVlmRexmzz5KKQkfnI3gXopgtJVYie1HyJtiDhlLC781hSXLNZUOxO+yotaGBIQGYcA3QABPfA092bJQTS6fGIo/tfFWPRSg2dvgqVT6YOjZITAzIJDgePGCjhDMgqNSCpZBgH+0FDaCrauQdbuVPn4vdQdfy12AR5EN5X1ioEoB3tysPKeK9JrOFa8pwlJtGr1Mq+apWtpMM/x0Sg7hkqgBm6zxL+P31+LNSNyXIRZA2b757UHYi++pVSNV0JDRUGbhyMOJxucmM2ZW5pk983MolgyC57i/uBsRHu0EThneCIU+ODlkQncDPjo3sfC6OOohuVwtD/r8xsEskf20RQC4HzlhavpAWdVxr4ozHsDVcPGzpGKH5Jap087Uq9NR/mZCQpz2YFQg3DisK0yCzIGBl8+xH1hA/raPOvgWnzG6OlxCZY3X5/So4EUc5StWsyh9ytX+Z4c/EQZcFLbhgUMx0pkugZQ3AMkvzdJUyD9DDXTFE2P/WQQuckcl+98thSqLw9OplizO9fenxbtPCs+hjoruNw2x06nwT1YcX49NavnrGMN8RRZE0pAdHESoVkr1WjYDzLB4NAYFrxUnQVxpzQOPtGRXI2gn6ngSdF2IEiwsuUCxrg7w=
